### ISSUE TITLE
建议一个新功能

### ISSUE THREAD

**Issue by LeeReindeer** [XF-zhjnc/CloudMusicXposed#1]
- 主题换肤里的自选颜色(现在需要反复的滑动颜色条,才能出输入颜色代码的dialog,很麻烦).
- 如果可以hook成点击一下就跳出dialog,会方便许多.
- 不知这个能否实现?

**Comment by xeemoo** [comment]
@LeeReindeer OK，我已经找到了该功能的代码，这么隐蔽的弹窗也能发现(更改颜色666次才会触发)，挺厉害呀哈哈。另外去除版权限制功能在v4.1.3的云音乐中失效了，估计我要一并解决才会发布新版本，感谢你的提议和关注^_^

**Comment by xeemoo** [comment]
@LeeReindeer  v2.2版本已支持此功能，在右上角加了个menu，点击即可跳出dialog

**Comment by LeeReindeer** [comment]
@XF-zhjnc Thanks.
