### ISSUE TITLE
5.4.1?

### ISSUE THREAD

**Issue by ertmuirm** [XF-zhjnc/CloudMusicXposed#2]
支持5.4.1版本吗？ 如何下载apk? 谢谢！

**Comment by xeemoo** [comment]
@ertmuirm 暂不支持，过两天有空更新。因为经常换着电脑工作，签名文件没有随身带所以就一直没上传apk，`git clone` 切换到 `SingleVersionSupport` 分支自行编译即可，遇到问题可以贴出来。

**Comment by ertmuirm** [comment]
@XF-zhjnc 谢谢！

**Comment by xeemoo** [comment]
@ertmuirm 支持5.4.1，不需要修改
